### PR TITLE
Extract util functions and organize code

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by wraithgar** [comment]
Gonna need to add `libs/utils.js` to the `files` section in package.json

**Comment by pgilad** [comment]
Yeah, you're absolutely right..

**Comment by wraithgar** [comment]
+1 looks like a good refactor that could eventually lead to a separate micro library.

**Comment by pgilad** [comment]
@bear can you review as well?

**Comment by bear** [comment]
+1 nice layer to abstract, and I agree with @wraithgar about it possibly becoming a separate support library

nicely done

**Comment by pgilad** [comment]
Thanks guys for the review!

**Pull request merged**
