### PR TITLE
Update lodash to v4

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by cdaringe** [comment]
i haven't run the tests locally, but looks great! +1

**Comment by lukekarrys** [comment]
+1, thanks for doing this :smile:

**Comment by pgilad** [comment]
Are we good with the merge? Who is bumping versions and to what?

**Comment by wraithgar** [comment]
This will be a major because even if the API isn't changing this represents a huge shift in what will be built, and a major semver will allow us to constrain all the lodash 4 modules together and not bloat peoples' builds.

**Comment by dschissler** [comment]
@pgilad I can begin using any updated modules with the new lodash version as long as it is compatible with the other modules being installed at the same time.  I'm far from production and so bundle sizes don't matter at all.  I don't have my head into this so I'm not exactly sure of the current state of it.  If you give me simple instructions and point me to the correct places then I can bang on this a lot in a real program.

[edit] Also I'm on npm `3.3.12`.

**Comment by wraithgar** [comment]
published as `v2.0.0`

@dschissler this should Just Work™ out of the box, albeit with larger build sizes.  You won't really be testing much unless you have something that explicitly requires this module, since all the other ampersand modules are requiring `^1.1.1` or lower.

**Pull request merged**
