### PR TITLE
Add bind/unbind for backwards compatibility

### PR DESCRIPTION
**Pull request by latentflip**
q

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1 visual

**Comment by wraithgar** [comment]
Readme?

**Comment by latentflip** [comment]
@wraithgar think it's worth it?

**Comment by latentflip** [comment]
@gar okay added

**Comment by latentflip** [comment]
Urgh, which has just kicked off travis again.

**Comment by wraithgar** [comment]
Published as `v1.1.0`

**Pull request merged**
