### PR TITLE
Adds sensible error messages if listenTo is trying to listen to undefined or a non-amp-events object

### PR DESCRIPTION
**Pull request by latentflip**
Got fed up of: 

665deb60-57b4-4eda-9131-3d0a287ef91f 2015-05-24 21-08-47

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1

**Comment by kamilogorek** [comment]
+1

@bear can we strip <IE9 for a whole Ampersand org. on Travis? Right now they're causing CI to fail, eg. in this very ticket.

**Comment by bear** [comment]
Once this build passes I'll make the zuul change across the repos

**Comment by latentflip** [comment]
Okay, gonna merge this, it'll still run just the same as it did before in ie6/7/8 anyway, it just may not error in exactly this place.

**Pull request merged**
